development:
  adapter: postgresql
  database: conductor_example_development
  username: postgres
  password:
  host: 127.0.0.1

test:
  adapter: postgresql
  database: conductor_example_test
  username: postgres
  password:
  host: 127.0.0.1

production:
  adapter: postgresql
  database: conductor_example_production
  username: postgres
  password:
  host: 127.0.0.1
